### ISSUE TITLE
Ability to chose channels 

### ISSUE THREAD

**Issue by kevinduterne** [ChasonDeshotel/Reloop-RP-8000-MIDI#2]
First of all thank you for the great work reverse engineering this undocumented turntable ! 

I'm trying to set the second channel when daisy chaining two RP8000-mk2's 
Do you by any chance know what the channel bits are ? 
If not how did you figure out the get the right values to send bpm to the player ? 

Any help appreciated ! 

Thx

**Comment by ChasonDeshotel** [comment]
Wow! Thank you! So sorry I missed your comment

>I'm trying to set the second channel when daisy chaining two RP8000-mk2's
>Do you by any chance know what the channel bits are ?

I totally forgot you could do that. I have 3 hooked up but I run them all to a hub

If by channel you mean which deck the unit is set to, I'm not going to say there's no way to set this programmatically--I didn't dig into the startup sequence--but in Serato, a software this turntable tightly integrates with and was no doubt designed for, you have to set the deck via buttons on the turntable... so I'm guessing they didn't put development time into making that available via SysEx

If by channel you mean MIDI channel, afaik they're always set to channel 1 and you communicate via establishing connection with the correct virtual MIDI device

>If not how did you figure out the get the right values to send bpm to the player ?

The decks use standard MIDI to communicate, so I used [MIDI Monitor ](https://www.snoize.com/MIDIMonitor/) to snoop. I know the MIDI protocol decently well, so when I saw the values come through I was able to identify the data as a stream of SysEx messages. From there, I wrote a Py script (early stages of this codebase) to strip out the SysEx header and print the values and to send messages back to the deck

Sending data to the decks had no effect (even data I'd previously captured) so I went back to MIDI Monitor to see if anything happened when I launched Serato. Well, it turns out Serato does spam something on startup. I captured this and replayed it via my script and boom, sending messages updates the display

Not all of the numbers worked though, so I documented the edge cases, hurt my brain for a couple hours trying to solve this puzzle, and asked the question on stack. Bavi H came through with the missing piece

https://reverseengineering.stackexchange.com/questions/25162/construct-a-number-from-0-999-9-using-5-data-bytes-of-a-midi-sysex-message

edit: Thanks for providing the fix! Just saw your PR

Issue solved/closed. Merged with https://github.com/ChasonDeshotel/Reloop-RP-8000-MIDI/pull/1
